name: bigdata
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-bigdata
    privileged: true
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/data/mongo/bigdata:/data/db
      - ./volumes/logs/mongo/bigdata:/var/log/mongodb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: ["mongod"]